micronaut:
  application:
    name: demo

endpoints:
  caches:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
---
micronaut:
  caches:
    headlines:
      maximum-size: 100000
      record-stats: true
      expire-after-write: 10080m